spring:
    application:
        name: restAop
    sql:
        init:
            mode: always
    datasource:
        url: jdbc:postgresql://localhost:5432/Tasks
        username: postgres
        password: filds17A
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
    kafka:
        bootstrap-servers: localhost:29092
        consumer:
            group-id: my-group
            auto-offset-reset: earliest